#!/bin/zsh

# Create backup directory
mkdir ~/dotfiles_backup

# Backup files and directories
(ls ~/.bash_profile 2>/dev/null && mv ~/.bash_profile ~/dotfiles_backup) || echo 'bash_profile not backupped'
(ls ~/.bashrc 2>/dev/null && mv ~/.bashrc ~/dotfiles_backup) || echo 'bashrc not backupped'
(ls ~/.config/nvim 2>/dev/null && mv ~/.nvim ~/dotfiles_backup) || echo 'nvim not backupped'
(ls ~/.config 2>/dev/null && mv ~/.config ~/dotfiles_backup) || echo 'config dir not backupped'
(ls ~/.editorconfig 2>/dev/null && mv ~/.editorconfig ~/dotfiles_backup) || echo 'editorconfig not backupped'
(ls ~/.generalrc 2>/dev/null && mv ~/.generalrc ~/dotfiles_backup) || echo 'generalrc not backupped'
(ls ~/.oh-my-zsh 2>/dev/null && mv ~/.oh-my-zsh ~/dotfiles_backup) || echo 'oh-my-zsh not backupped'
(ls ~/.profile 2>/dev/null && mv ~/.profile ~/dotfiles_backup) || echo 'profile not backupped'
(ls ~/.psqlrc 2>/dev/null && mv ~/.psqlrc ~/dotfiles_backup) || echo 'psqlrc not backupped'
(ls ~/.scripts 2>/dev/null && mv ~/.scripts ~/dotfiles_backup) || echo 'scripts not backupped'
(ls ~/.tmux.conf 2>/dev/null && mv ~/.tmux.conf ~/dotfiles_backup) || echo 'tmux conf not backupped'
(ls ~/.vim 2>/dev/null && mv ~/.vim ~/dotfiles_backup) || echo 'vim dir not backupped'
(ls ~/.zshrc 2>/dev/null && mv ~/.zshrc ~/dotfiles_backup) || echo 'zshrc not backupped'
mv ~/dotfiles_backup ~/dotfiles_backup_$(date "+%d-%m-%Y-%T")

# Link files
ln -sv $(pwd)/.bash_profile $HOME
ln -sv $(pwd)/.bashrc $HOME
ln -sv $(pwd)/.config $HOME
ln -sv $(pwd)/.editorconfig $HOME
ln -sv $(pwd)/.generalrc $HOME
ln -sv $(pwd)/.nvim "$HOME/.config/nvim"
ln -sv $(pwd)/.oh-my-zsh $HOME
ln -sv $(pwd)/.profile $HOME
ln -sv $(pwd)/.psqlrc $HOME
ln -sv $(pwd)/.scripts $HOME
ln -sv $(pwd)/.tmux.conf $HOME
ln -sv $(pwd)/.vimrc $HOME
ln -sv $(pwd)/.zshrc $HOME

# Install oh-my-zsh
(ls ~/.oh-my-zsh 2>/dev/null && mv ~/.oh-my-zsh ~/dotfiles_backup) || echo 'oh-my-zsh directory not backupped'
mv .oh-my-zsh .oh-my-zsh.bak
git clone https://github.com/robbyrussell/oh-my-zsh.git .oh-my-zsh
mv .oh-my-zsh.bak/themes/luciano.zsh-theme .oh-my-zsh/themes
rm -rf .oh-my-zsh.bak
ln -sv $(pwd)/.oh-my-zsh $HOME

# Done!
echo 'Done!'

