#!/bin/sh

cpu() {
    echo "" &&
    top -bn1 | grep "Cpu(s)" | \
        sed "s/.*, *\\([0-9.]*\\)%* id.*/\\1/" | \
        awk '{print 100 - $1}' | \
        xargs -I {} printf "%4.4s" "{}" &&
    echo '%'
}

memory() {
    echo "" &&
    free -h | \
        grep Mem | \
        awk '{ print $3 "/" $2 }' | \
        sed 's/Gi/G/g'
}

weather() {
    sed '16q;d' "$HOME/.local/share/weatherreport" | \
        grep -wo "[0-9]*%" | \
        sort -n | \
        sed -e '$!d' | \
        sed -e "s/^/ /g" | \
        tr -d '\n' &&
    sed '13q;d' "$HOME/.local/share/weatherreport" | \
        grep -o "m\\(-\\)*[0-9]\\+" | \
        sort -n -t 'm' -k 2n | \
        sed -e 1b -e '$!d' | \
        tr '\n|m' ' ' | \
        awk '{print " ",$1 "°","",$2 "°"}'
}

wifi() {
    grep "^\\s*w" /proc/net/wireless | awk '{ print "", int($3 * 100 / 70) "%" }'
    sed "s/down//;s/up//" /sys/class/net/e*/operstate
}

email() {
    command -v mw >/dev/null 2>&1 &&
    du -a ~/.local/share/mail/*/INBOX/new/* 2>/dev/null | \
        wc -l | \
        sed 's/^/:/'
}

battery() {
    for x in /sys/class/power_supply/BAT?/capacity;
    do
    case "$(cat $x)" in
        100|9[0-9]) echo "" ;;
        8[0-9]|7[0-9]) echo "" ;;
        6[0-9]|5[0-9]) echo "" ;;
        4[0-9]|3[0-9]) echo "" ;;
        *)  echo "" ;;
    esac
    cat "$x"
    echo "%"
    done
}

bardate() {
    date '+%Y %b %d (%a) %I:%M:%S%p %:z'
}

delim () {
    echo ' | '
}

statusbar() {
    echo ' '
    weather
        delim
    cpu
        delim
    memory
        delim
    wifi
        delim
    email
        delim
    battery
        delim
    bardate
}

statusbarstring () {
    echo "$(statusbar | tr '\n' ' ' | tr -s ' ' | sed 's/ %/%/')"
}

update () {
    xsetroot -name "$(statusbarstring)" &
    wait
}

while :; do
    #time update # For debugging/development
    update
	sleep 0.5 &
    wait
done


